//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesReservation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_AirlinesReservationEntities : DbContext
    {
        public DB_AirlinesReservationEntities()
            : base("name=DB_AirlinesReservationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Chair> Chair { get; set; }
        public virtual DbSet<DB_user> DB_user { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<Emloyee> Emloyee { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<Round_Trip> Round_Trip { get; set; }
        public virtual DbSet<Seat> Seat { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
    }
}
