//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DB_user()
        {
            this.Booking = new HashSet<Booking>();
            this.Round_Trip = new HashSet<Round_Trip>();
            this.Ticket = new HashSet<Ticket>();
        }
    
        public string User_id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Address { get; set; }
        public string Phone_number { get; set; }
        public string Email_address { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string Credit_card { get; set; }
        public Nullable<int> Sky_miles { get; set; }
        public string Password { get; set; }
        public string Img { get; set; }
        public string Passport { get; set; }
        public Nullable<int> Status { get; set; }
        public string Bank_Name { get; set; }
        public string Credit_Name { get; set; }
        public string CVV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Round_Trip> Round_Trip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
