//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public string Discount_id { get; set; }
        public Nullable<int> Flight_id { get; set; }
        public Nullable<int> Discount1 { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
