//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emloyee
    {
        public int Employee_id { get; set; }
        public string Full_name { get; set; }
        public string Img { get; set; }
        public string Email { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Address { get; set; }
        public string User_name { get; set; }
        public string Password { get; set; }
        public Nullable<int> Roles { get; set; }
    }
}
