//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesReservation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round_Trip
    {
        public int Roundtrip_id { get; set; }
        public string User_id { get; set; }
        public Nullable<int> Seat_id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual DB_user DB_user { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
